### PR TITLE
Merge value of rules with the same key

### PR DESCRIPTION
**Pull request by davidbonnet**
# Motivation

CSS at-rules can occur several times in a CSS file. Yet, only the latest one is kept when converting to JSS. This PR tackles this issue.

### CODE REVIEW

**Comment by davidbonnet** [comment]
Actually, it should use [fallbacks](http://cssinjs.org/json-api/?v=v9.0.0#fallbacks) for multiple properties. Updating…

**Comment by kof** [comment]
LGTM! CLI has currently no tests, you sure it works? Have you tried to convert a complex file and verify the results?

**Comment by davidbonnet** [comment]
I tested it on the [Bootstrap CSS file (version 3)](https://github.com/twbs/bootstrap/blob/v3-dev/dist/css/bootstrap.css). Initial results led to quite incomplete styles, which motivated this PR.

**Comment by kof** [comment]
merged

**Comment by kof** [comment]
Released as v5 with update of JSS and presets! Thanks a lot!

**Pull request merged**
